# SPDX-License-Identifier: GPL-3.0-or-later
version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      rust:
        patterns: ["*"]
        update-types: [minor, patch]
  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: weekly
    groups:
      android:
        patterns: ["*"]
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
