// SPDX-License-Identifier: GPL-3.0-or-later
// Generated from docs/design/tokens.json by `cargo xtask tokens`. Do not edit.
package app.nectarlink.android.ui.theme

import androidx.compose.ui.graphics.Color

/** Material color roles of one theme variant. */
data class Palette(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val surface: Color,
    val surfaceContainerLow: Color,
    val surfaceContainer: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color,
    val onSurface: Color,
    val onSurfaceVariant: Color,
    val outline: Color,
    val outlineVariant: Color,
)

/** A Bloom color preset: its seed swatch and light and dark palettes. */
data class Seed(val color: Color, val light: Palette, val dark: Palette)

object Tokens {
    const val DEFAULT_SEED = "honey"

    val bloomSeeds: Map<String, Seed> = linkedMapOf(
        "honey" to Seed(
            color = Color(0xFFB7791F),
            light = Palette(
                primary = Color(0xFF8A5100),
                onPrimary = Color(0xFFFFFFFF),
                primaryContainer = Color(0xFFFFDDB8),
                onPrimaryContainer = Color(0xFF2C1600),
                secondaryContainer = Color(0xFFF3E0CB),
                onSecondaryContainer = Color(0xFF261A0C),
                surface = Color(0xFFFFF8F3),
                surfaceContainerLow = Color(0xFFFBF2EB),
                surfaceContainer = Color(0xFFF5ECE4),
                surfaceContainerHigh = Color(0xFFEFE6DE),
                surfaceContainerHighest = Color(0xFFE9E1D9),
                onSurface = Color(0xFF1F1B16),
                onSurfaceVariant = Color(0xFF51453A),
                outline = Color(0xFF837468),
                outlineVariant = Color(0xFFD5C3B5),
            ),
            dark = Palette(
                primary = Color(0xFFFFB95F),
                onPrimary = Color(0xFF4A2800),
                primaryContainer = Color(0xFF693C00),
                onPrimaryContainer = Color(0xFFFFDDB8),
                secondaryContainer = Color(0xFF574330),
                onSecondaryContainer = Color(0xFFF3E0CB),
                surface = Color(0xFF17130E),
                surfaceContainerLow = Color(0xFF120E0A),
                surfaceContainer = Color(0xFF241F1A),
                surfaceContainerHigh = Color(0xFF2E2924),
                surfaceContainerHighest = Color(0xFF39342E),
                onSurface = Color(0xFFEBE1D9),
                onSurfaceVariant = Color(0xFFD5C3B5),
                outline = Color(0xFF9E8E81),
                outlineVariant = Color(0xFF51453A),
            ),
        ),
        "lavender" to Seed(
            color = Color(0xFF7E6AA8),
            light = Palette(
                primary = Color(0xFF65558F),
                onPrimary = Color(0xFFFFFFFF),
                primaryContainer = Color(0xFFE9DDFF),
                onPrimaryContainer = Color(0xFF201047),
                secondaryContainer = Color(0xFFE8DEF8),
                onSecondaryContainer = Color(0xFF1D192B),
                surface = Color(0xFFFDF7FF),
                surfaceContainerLow = Color(0xFFF7F2FA),
                surfaceContainer = Color(0xFFF2ECF4),
                surfaceContainerHigh = Color(0xFFECE6EE),
                surfaceContainerHighest = Color(0xFFE6E0E9),
                onSurface = Color(0xFF1D1B20),
                onSurfaceVariant = Color(0xFF49454E),
                outline = Color(0xFF7A757F),
                outlineVariant = Color(0xFFCAC4CF),
            ),
            dark = Palette(
                primary = Color(0xFFCFBDFE),
                onPrimary = Color(0xFF36275D),
                primaryContainer = Color(0xFF4D3D75),
                onPrimaryContainer = Color(0xFFE9DDFF),
                secondaryContainer = Color(0xFF4A4458),
                onSecondaryContainer = Color(0xFFE8DEF8),
                surface = Color(0xFF141218),
                surfaceContainerLow = Color(0xFF0F0D13),
                surfaceContainer = Color(0xFF211F24),
                surfaceContainerHigh = Color(0xFF2B292F),
                surfaceContainerHighest = Color(0xFF36343A),
                onSurface = Color(0xFFE6E0E9),
                onSurfaceVariant = Color(0xFFCAC4CF),
                outline = Color(0xFF948F99),
                outlineVariant = Color(0xFF49454E),
            ),
        ),
        "ocean" to Seed(
            color = Color(0xFF3D7DA8),
            light = Palette(
                primary = Color(0xFF2F628C),
                onPrimary = Color(0xFFFFFFFF),
                primaryContainer = Color(0xFFCEE5FF),
                onPrimaryContainer = Color(0xFF001D33),
                secondaryContainer = Color(0xFFD5E4F7),
                onSecondaryContainer = Color(0xFF0E1D2A),
                surface = Color(0xFFF7F9FF),
                surfaceContainerLow = Color(0xFFF1F4FA),
                surfaceContainer = Color(0xFFECEEF4),
                surfaceContainerHigh = Color(0xFFE6E8EE),
                surfaceContainerHighest = Color(0xFFE0E2E8),
                onSurface = Color(0xFF181C20),
                onSurfaceVariant = Color(0xFF42474E),
                outline = Color(0xFF72777F),
                outlineVariant = Color(0xFFC2C7CF),
            ),
            dark = Palette(
                primary = Color(0xFF9BCBFB),
                onPrimary = Color(0xFF003354),
                primaryContainer = Color(0xFF0F4A73),
                onPrimaryContainer = Color(0xFFCEE5FF),
                secondaryContainer = Color(0xFF3B4858),
                onSecondaryContainer = Color(0xFFD5E4F7),
                surface = Color(0xFF101418),
                surfaceContainerLow = Color(0xFF0B0F13),
                surfaceContainer = Color(0xFF1C2024),
                surfaceContainerHigh = Color(0xFF262A2F),
                surfaceContainerHighest = Color(0xFF31353A),
                onSurface = Color(0xFFE0E2E8),
                onSurfaceVariant = Color(0xFFC2C7CF),
                outline = Color(0xFF8C9199),
                outlineVariant = Color(0xFF42474E),
            ),
        ),
        "sage" to Seed(
            color = Color(0xFF5B8C5A),
            light = Palette(
                primary = Color(0xFF3B6939),
                onPrimary = Color(0xFFFFFFFF),
                primaryContainer = Color(0xFFBCF0B4),
                onPrimaryContainer = Color(0xFF002204),
                secondaryContainer = Color(0xFFD6E8CF),
                onSecondaryContainer = Color(0xFF111F0F),
                surface = Color(0xFFF7FBF1),
                surfaceContainerLow = Color(0xFFF1F5EB),
                surfaceContainer = Color(0xFFEBEFE5),
                surfaceContainerHigh = Color(0xFFE6E9E0),
                surfaceContainerHighest = Color(0xFFE0E4DA),
                onSurface = Color(0xFF191D17),
                onSurfaceVariant = Color(0xFF424940),
                outline = Color(0xFF72796F),
                outlineVariant = Color(0xFFC2C8BD),
            ),
            dark = Palette(
                primary = Color(0xFFA1D39A),
                onPrimary = Color(0xFF0A390F),
                primaryContainer = Color(0xFF234F24),
                onPrimaryContainer = Color(0xFFBCF0B4),
                secondaryContainer = Color(0xFF3B4B38),
                onSecondaryContainer = Color(0xFFD6E8CF),
                surface = Color(0xFF10140F),
                surfaceContainerLow = Color(0xFF0C100B),
                surfaceContainer = Color(0xFF1D211B),
                surfaceContainerHigh = Color(0xFF272B25),
                surfaceContainerHighest = Color(0xFF32362F),
                onSurface = Color(0xFFE0E4DA),
                onSurfaceVariant = Color(0xFFC2C8BD),
                outline = Color(0xFF8C9388),
                outlineVariant = Color(0xFF424940),
            ),
        ),
    )

    val graphitePaper = Palette(
        primary = Color(0xFF1A1918),
        onPrimary = Color(0xFFF5F2EB),
        primaryContainer = Color(0xFFE8E3D7),
        onPrimaryContainer = Color(0xFF1A1918),
        secondaryContainer = Color(0xFFE8E3D7),
        onSecondaryContainer = Color(0xFF1A1918),
        surface = Color(0xFFF5F2EB),
        surfaceContainerLow = Color(0xFFF1EDE4),
        surfaceContainer = Color(0xFFF5F2EB),
        surfaceContainerHigh = Color(0xFFEFEBE2),
        surfaceContainerHighest = Color(0xFFE8E3D7),
        onSurface = Color(0xFF1A1918),
        onSurfaceVariant = Color(0xFF5E5A54),
        outline = Color(0xFF4A4743),
        outlineVariant = Color(0xFFD5CFC2),
    )

    val graphiteSlate = Palette(
        primary = Color(0xFFE8EAED),
        onPrimary = Color(0xFF0D0D0E),
        primaryContainer = Color(0xFF1A1A1D),
        onPrimaryContainer = Color(0xFFE8EAED),
        secondaryContainer = Color(0xFF1A1A1D),
        onSecondaryContainer = Color(0xFFE8EAED),
        surface = Color(0xFF0D0D0E),
        surfaceContainerLow = Color(0xFF0B0B0C),
        surfaceContainer = Color(0xFF0D0D0E),
        surfaceContainerHigh = Color(0xFF141416),
        surfaceContainerHighest = Color(0xFF1A1A1D),
        onSurface = Color(0xFFE8EAED),
        onSurfaceVariant = Color(0xFF9A9CA1),
        outline = Color(0xFF7E8084),
        outlineVariant = Color(0xFF26272A),
    )

    val warningLight = Color(0xFF9A6700)
    val warningDark = Color(0xFFF2C14E)
    val errorLight = Color(0xFFBA1A1A)
    val errorDark = Color(0xFFFFB4AB)
}
