[package]
name = "nectarlink-core"
description = "Nectarlink engine: identity, pairing, sessions and storage"
license = "MPL-2.0"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
nectarlink-protocol.workspace = true

[lints]
workspace = true
